name: Build, Deploy, and Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Echo Git Context
        run: |
          echo "event_name: ${{ github.event_name }}"
          echo "ref: ${{ github.ref }}"
          echo "ref_name: ${{ github.ref_name }}"
          echo "base_ref: ${{ github.base_ref }}"
          echo "head_ref: ${{ github.head_ref }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Extract version number
        id: extract_version
        run: |
          $content = Get-Content -Path randomizer.py
          $version = ($content | Select-String -Pattern "VERSION = '([0-9.]+[a-z]?)'" -AllMatches).Matches.Groups[1].Value
          echo "VERSION=$version" >> $env:GITHUB_ENV

      - name: Build with PyInstaller
        run: pyinstaller randomizer.spec

      - name: Package into a self-extracting exe using 7z
        run: |
          mkdir deploy
          mkdir deploy/fftrctcr_v${{ env.VERSION }}
          Copy-Item -Recurse -Path dist\fftrctcr.exe, custom\, create_seed_fftrctcr.bat -Destination deploy\fftrctcr_v${{ env.VERSION }}\
          cd deploy 
          7z a -t7z -mx=9 -ms=on ..\fftrctcr_v${{ env.VERSION }}.7z fftrctcr_v${{ env.VERSION }}\*
          7z a -sfx7z.sfx -mmt=on -mx=9 -mfb=256 -md=64m -ms=on -mhe=on -sfx fftrctcr_v${{ env.VERSION }}.exe fftrctcr_v${{ env.VERSION }}.7z

      - name: Create/Update Release
        if: always()
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: deploy/fftrctcr_v${{ env.VERSION }}.exe
          release_name: "FINAL FANTASY TACTICS Rumble: Chaos: >>The Crashdown<< REMAKE ${{ env.VERSION }}"
          prerelease: false
          tag: v${{ env.VERSION }}
          overwrite: true
          body: "fftrctcr version ${{ env.VERSION }}"
